package model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_admin", "id", Admin.class);
		arp.addMapping("t_buy_record", "id", BuyRecord.class);
		arp.addMapping("t_channel", "id", Channel.class);
		arp.addMapping("t_chapter", "id", Chapter.class);
		arp.addMapping("t_classify", "id", Classify.class);
		arp.addMapping("t_comment", "id", Comment.class);
		arp.addMapping("t_config", "id", Config.class);
		arp.addMapping("t_giving", "id", Giving.class);
		arp.addMapping("t_history", "id", History.class);
		arp.addMapping("t_novel", "id", Novel.class);
		arp.addMapping("t_readTimes", "id", Readtimes.class);
		arp.addMapping("t_recharge", "id", Recharge.class);
		arp.addMapping("t_sign_in", "id", SignIn.class);
		arp.addMapping("t_statistic", "id", Statistic.class);
		arp.addMapping("t_user", "id", User.class);
		arp.addMapping("t_view_user", "id", ViewUser.class);
		arp.addMapping("t_property", "id", Property.class);
		arp.addMapping("t_original_poem", "originalId", OriginalPoem.class);
		arp.addMapping("t_poem", "id", Poem.class);
		arp.addMapping("t_poem_paragraph", "id", PoemParagraph.class);
	}
}

