package model;

import utils.DicUtil;

import com.alibaba.fastjson.JSONObject;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.ehcache.CacheKit;

import model.base.BaseConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Config extends BaseConfig<Config> {
	public static final Config dao = new Config();
	public static final String KEY_PRICE = "price" ; //小说千字价格
	public static final String KEY_GET_OPEN_ID = "getOpenId" ; //小说千字价格
	public static final String KEY_DEVIDED_TYPE = "devidedType" ; //分成收益方式
	
	public static final int KEY_DEVIDED_MODLE_1 = 1 ; //网站增益模式
	public static final int KEY_DEVIDED_MODLE_2 = 2 ; //渠道增益模式
	
	//清理缓存
	public JSONObject setValue(Config config) {
		String sql = "UPDATE t_config tc SET tc.value = ? WHERE tc.key = ? " ;
		Db.update(sql, config.getValue() , config.getKey());
		CacheKit.remove(DicUtil.CACHE_CONFIG, config.getKey()) ;
		return sendSuccessJson();
	}
	
	//缓存
	public Config findByKey(String key) {
		return this.findFirstByCache(DicUtil.CACHE_CONFIG, key, "SELECT tc.* FROM t_config tc WHERE tc.key = ? " , key ) ;
	}
	
	
}
