package model;

import java.util.Date;

import model.base.BaseReadtimes;
import utils.DicUtil;

import com.jfinal.plugin.ehcache.CacheKit;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Readtimes extends BaseReadtimes<Readtimes> {
	public static final Readtimes dao = new Readtimes().dao();
	
	public Readtimes get(String novelId , String date) {
		return this.findFirst(" SELECT tr.id , tr.readTimes FROM t_readTimes tr WHERE tr.novelId = ? AND tr.date = ? " , novelId , date ) ;
	}
	
	public void save(String novelId , String date) {
		Readtimes readtimes = this.get(novelId, date) ;
		Integer readTimes = (Integer) (null == CacheKit.get(DicUtil.CACHE_READTIMES, novelId) ? 0 : CacheKit.get(DicUtil.CACHE_READTIMES, novelId)) ;
		if (null == readtimes) {
			readtimes = new Readtimes() ;
			readtimes.setReadTimes(readTimes);
			readtimes.setNovelId(novelId) ;
			readtimes.set("date", date) ;
			readtimes.save() ;
		}else {
			readtimes.setReadTimes(readtimes.getReadTimes() + readTimes);
			readtimes.update();
		}
		CacheKit.remove(DicUtil.CACHE_READTIMES, novelId) ;
		CacheKit.removeAll(DicUtil.CACHE_MAX_READTIMES) ; //本周人气榜
	}
}
