package model;

import utils.DicUtil;
import model.base.BaseViewUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ViewUser extends BaseViewUser<ViewUser> {
	public static final ViewUser dao = new ViewUser().dao();
	
	/******************缓存存储*******************/
	public ViewUser findRecordInCache(String userId , String date) {
		String sql = "SELECT tv.id FROM t_view_user tv WHERE tv.userId = ? AND date = ? " ;
		return this.findFirstByCache(DicUtil.CACHE_VIEW_USER, userId + date , sql , userId , date ) ;
	}
	
	public void saveRecord(String userId , String date) {
		ViewUser viewUser = new ViewUser() ;
		viewUser.set("date", date) ;
		viewUser.setUserId(userId);
		viewUser.save() ;
	}
	
}
