package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseHistory<M extends BaseHistory<M>> extends _BaseModel<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setNovelId(java.lang.String novelId) {
		set("novelId", novelId);
	}

	public java.lang.String getNovelId() {
		return get("novelId");
	}

	public void setTime(java.util.Date time) {
		set("time", time);
	}

	public java.util.Date getTime() {
		return get("time");
	}

	public void setUserId(java.lang.String userId) {
		set("userId", userId);
	}

	public java.lang.String getUserId() {
		return get("userId");
	}

	public void setChapterNum(java.lang.Integer chapterNum) {
		set("chapterNum", chapterNum);
	}

	public java.lang.Integer getChapterNum() {
		return get("chapterNum");
	}

	public void setIsFavorite(java.lang.Boolean isFavorite) {
		set("isFavorite", isFavorite);
	}

	public java.lang.Boolean getIsFavorite() {
		return get("isFavorite");
	}

}
