package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRecharge<M extends BaseRecharge<M>> extends _BaseModel<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setUserId(java.lang.String userId) {
		set("userId", userId);
	}

	public java.lang.String getUserId() {
		return get("userId");
	}

	public void setAmount(java.lang.Integer amount) {
		set("amount", amount);
	}

	public java.lang.Integer getAmount() {
		return get("amount");
	}

	public void setTime(java.util.Date time) {
		set("time", time);
	}

	public java.util.Date getTime() {
		return get("time");
	}

	public void setEndTime(java.util.Date endTime) {
		set("endTime", endTime);
	}

	public java.util.Date getEndTime() {
		return get("endTime");
	}

	public void setTransId(java.lang.String transId) {
		set("transId", transId);
	}

	public java.lang.String getTransId() {
		return get("transId");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

	public void setStaticBalance(java.lang.Integer staticBalance) {
		set("staticBalance", staticBalance);
	}

	public java.lang.Integer getStaticBalance() {
		return get("staticBalance");
	}

	public void setGivings(java.lang.Integer givings) {
		set("givings", givings);
	}

	public java.lang.Integer getGivings() {
		return get("givings");
	}

	public void setGets(java.lang.Integer gets) {
		set("gets", gets);
	}

	public java.lang.Integer getGets() {
		return get("gets");
	}

	public void setChannelId(java.lang.String channelId) {
		set("channelId", channelId);
	}

	public java.lang.String getChannelId() {
		return get("channelId");
	}

	public void setNovelId(java.lang.String novelId) {
		set("novelId", novelId);
	}

	public java.lang.String getNovelId() {
		return get("novelId");
	}

	public void setNumber(java.lang.Integer number) {
		set("number", number);
	}

	public java.lang.Integer getNumber() {
		return get("number");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}

	public java.lang.Integer getType() {
		return get("type");
	}

	public void setPayType(java.lang.Integer payType) {
		set("payType", payType);
	}

	public java.lang.Integer getPayType() {
		return get("payType");
	}

}
