package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGiving<M extends BaseGiving<M>> extends _BaseModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setRechargeId(java.lang.String rechargeId) {
		set("rechargeId", rechargeId);
	}

	public java.lang.String getRechargeId() {
		return get("rechargeId");
	}

	public void setCoins(java.lang.Integer coins) {
		set("coins", coins);
	}

	public java.lang.Integer getCoins() {
		return get("coins");
	}

	public void setIsFinished(java.lang.Boolean isFinished) {
		set("isFinished", isFinished);
	}

	public java.lang.Boolean getIsFinished() {
		return get("isFinished");
	}

}
