package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends _BaseModel<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setNickname(java.lang.String nickname) {
		set("nickname", nickname);
	}

	public java.lang.String getNickname() {
		return get("nickname");
	}

	public void setPhoto(java.lang.String photo) {
		set("photo", photo);
	}

	public java.lang.String getPhoto() {
		return get("photo");
	}

	public void setChannelId(java.lang.String channelId) {
		set("channelId", channelId);
	}

	public java.lang.String getChannelId() {
		return get("channelId");
	}

	public void setOpenId(java.lang.String openId) {
		set("openId", openId);
	}

	public java.lang.String getOpenId() {
		return get("openId");
	}

	public void setToken(java.lang.String token) {
		set("token", token);
	}

	public java.lang.String getToken() {
		return get("token");
	}

	public void setCoins(java.lang.Integer coins) {
		set("coins", coins);
	}

	public java.lang.Integer getCoins() {
		return get("coins");
	}

	public void setSex(java.lang.String sex) {
		set("sex", sex);
	}

	public java.lang.String getSex() {
		return get("sex");
	}

	public void setRegistTime(java.util.Date registTime) {
		set("registTime", registTime);
	}

	public java.util.Date getRegistTime() {
		return get("registTime");
	}

	public void setScore(java.lang.Integer score) {
		set("score", score);
	}

	public java.lang.Integer getScore() {
		return get("score");
	}

	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}

	public java.lang.String getIp() {
		return get("ip");
	}

	public void setIsNew(java.lang.Boolean isNew) {
		set("isNew", isNew);
	}

	public java.lang.Boolean getIsNew() {
		return get("isNew");
	}

	public void setIsRecharged(java.lang.Boolean isRecharged) {
		set("isRecharged", isRecharged);
	}

	public java.lang.Boolean getIsRecharged() {
		return get("isRecharged");
	}

	public void setGetInfoTime(java.util.Date getInfoTime) {
		set("getInfoTime", getInfoTime);
	}

	public java.util.Date getGetInfoTime() {
		return get("getInfoTime");
	}

	public void setProvince(java.lang.String province) {
		set("province", province);
	}

	public java.lang.String getProvince() {
		return get("province");
	}

	public void setCity(java.lang.String city) {
		set("city", city);
	}

	public java.lang.String getCity() {
		return get("city");
	}
	
	public void setFocus(java.lang.Integer focus) {
		set("focus", focus);
	}

	public java.lang.Integer getFocus() {
		return get("focus");
	}
	
	public void setBlogerId(java.lang.Integer blogerId) {
		set("blogerId", blogerId);
	}

	public java.lang.Integer getBlogerId() {
		return get("blogerId");
	}

}
