package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNovel<M extends BaseNovel<M>> extends _BaseModel<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setNName(java.lang.String nName) {
		set("nName", nName);
	}

	public java.lang.String getNName() {
		return get("nName");
	}

	public void setClassifyId(java.lang.String classifyId) {
		set("classifyId", classifyId);
	}

	public java.lang.String getClassifyId() {
		return get("classifyId");
	}

	public void setReadTimes(java.lang.Integer readTimes) {
		set("readTimes", readTimes);
	}

	public java.lang.Integer getReadTimes() {
		return get("readTimes");
	}

	public void setDesc(java.lang.String desc) {
		set("desc", desc);
	}

	public java.lang.String getDesc() {
		return get("desc");
	}

	public void setAuthor(java.lang.String author) {
		set("author", author);
	}

	public java.lang.String getAuthor() {
		return get("author");
	}

	public void setPic(java.lang.String pic) {
		set("pic", pic);
	}

	public java.lang.String getPic() {
		return get("pic");
	}

	public void setCollectNum(java.lang.Integer collectNum) {
		set("collectNum", collectNum);
	}

	public java.lang.Integer getCollectNum() {
		return get("collectNum");
	}

	public void setIncome(java.lang.Integer income) {
		set("income", income);
	}

	public java.lang.Integer getIncome() {
		return get("income");
	}

	public void setIsEnd(java.lang.Boolean isEnd) {
		set("isEnd", isEnd);
	}

	public java.lang.Boolean getIsEnd() {
		return get("isEnd");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setCount(java.lang.Integer count) {
		set("count", count);
	}

	public java.lang.Integer getCount() {
		return get("count");
	}

	public void setExIncome(java.lang.Integer exIncome) {
		set("exIncome", exIncome);
	}

	public java.lang.Integer getExIncome() {
		return get("exIncome");
	}

	public void setFreeNum(java.lang.Integer freeNum) {
		set("freeNum", freeNum);
	}

	public java.lang.Integer getFreeNum() {
		return get("freeNum");
	}

	public void setRecommendNum(java.lang.Integer recommendNum) {
		set("recommendNum", recommendNum);
	}

	public java.lang.Integer getRecommendNum() {
		return get("recommendNum");
	}

	public void setFChapterId(java.lang.String fChapterId) {
		set("fChapterId", fChapterId);
	}

	public java.lang.String getFChapterId() {
		return get("fChapterId");
	}

	public void setLChapterId(java.lang.String lChapterId) {
		set("lChapterId", lChapterId);
	}

	public java.lang.String getLChapterId() {
		return get("lChapterId");
	}

	public void setLChapterNum(java.lang.Integer lChapterNum) {
		set("lChapterNum", lChapterNum);
	}

	public java.lang.Integer getLChapterNum() {
		return get("lChapterNum");
	}

	public void setLChapterTitle(java.lang.String lChapterTitle) {
		set("lChapterTitle", lChapterTitle);
	}

	public java.lang.String getLChapterTitle() {
		return get("lChapterTitle");
	}

	public void setOrderNum(java.lang.Integer orderNum) {
		set("orderNum", orderNum);
	}

	public java.lang.Integer getOrderNum() {
		return get("orderNum");
	}

}
