package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePoem<M extends BasePoem<M>> extends _BaseModel<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}

	public java.lang.String getTitle() {
		return get("title");
	}

	public void setClassifyId(java.lang.String classifyId) {
		set("classifyId", classifyId);
	}

	public java.lang.String getClassifyId() {
		return get("classifyId");
	}

	public void setTheme(java.lang.String theme) {
		set("theme", theme);
	}

	public java.lang.String getTheme() {
		return get("theme");
	}

	public void setAuthor(java.lang.String author) {
		set("author", author);
	}

	public java.lang.String getAuthor() {
		return get("author");
	}

	public void setDynasty(java.lang.String dynasty) {
		set("dynasty", dynasty);
	}

	public java.lang.String getDynasty() {
		return get("dynasty");
	}

	public void setAppreciation(java.lang.String appreciation) {
		set("appreciation", appreciation);
	}

	public java.lang.String getAppreciation() {
		return get("appreciation");
	}

	public void setAudio(java.lang.String audio) {
		set("audio", audio);
	}

	public java.lang.String getAudio() {
		return get("audio");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setNote(java.lang.String note) {
		set("note", note);
	}

	public java.lang.String getNote() {
		return get("note");
	}
	
	public void setRecommendNum(java.lang.Integer recommendNum) {
		set("recommendNum", recommendNum);
	}

	public java.lang.Integer getRecommendNum() {
		return get("recommendNum");
	}
	
	public void setCollectNum(java.lang.Integer collectNum) {
		set("collectNum", collectNum);
	}

	public java.lang.Integer getCollectNum() {
		return get("collectNum");
	}
	
	public void setPicture(java.lang.String picture) {
		set("picture", picture);
	}

	public java.lang.String getPicture() {
		return get("picture");
	}
}
