package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClassify<M extends BaseClassify<M>> extends _BaseModel<M> implements IBean {

	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setCName(java.lang.String cName) {
		set("cName", cName);
	}

	public java.lang.String getCName() {
		return get("cName");
	}

	public void setParentId(java.lang.String parentId) {
		set("parentId", parentId);
	}

	public java.lang.String getParentId() {
		return get("parentId");
	}

	public void setOrderNum(java.lang.Integer orderNum) {
		set("orderNum", orderNum);
	}

	public java.lang.Integer getOrderNum() {
		return get("orderNum");
	}

	public void setChildrenNum(java.lang.Integer childrenNum) {
		set("childrenNum", childrenNum);
	}

	public java.lang.Integer getChildrenNum() {
		return get("childrenNum");
	}

}
