package model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStatistic<M extends BaseStatistic<M>> extends _BaseModel<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setDate(java.util.Date date) {
		set("date", date);
	}

	public java.util.Date getDate() {
		return get("date");
	}

	public void setHour(java.lang.Integer hour) {
		set("hour", hour);
	}

	public java.lang.Integer getHour() {
		return get("hour");
	}

	public void setIncome(java.lang.Integer income) {
		set("income", income);
	}

	public java.lang.Integer getIncome() {
		return get("income");
	}

	public void setClicks(java.lang.Integer clicks) {
		set("clicks", clicks);
	}

	public java.lang.Integer getClicks() {
		return get("clicks");
	}

	public void setUv(java.lang.Integer uv) {
		set("uv", uv);
	}

	public java.lang.Integer getUv() {
		return get("uv");
	}

	public void setPv(java.lang.Integer pv) {
		set("pv", pv);
	}

	public java.lang.Integer getPv() {
		return get("pv");
	}

	public void setIp(java.lang.Integer ip) {
		set("ip", ip);
	}

	public java.lang.Integer getIp() {
		return get("ip");
	}

	public void setRegisters(java.lang.Integer registers) {
		set("registers", registers);
	}

	public java.lang.Integer getRegisters() {
		return get("registers");
	}

	public void setRechargers(java.lang.Integer rechargers) {
		set("rechargers", rechargers);
	}

	public java.lang.Integer getRechargers() {
		return get("rechargers");
	}

	public void setChannelId(java.lang.String channelId) {
		set("channelId", channelId);
	}

	public java.lang.String getChannelId() {
		return get("channelId");
	}

}
