package config;

import com.jfinal.plugin.activerecord.generator.BaseModelGenerator;
import com.jfinal.plugin.activerecord.generator.TableMeta;

public class ResetBaseModelGenerator extends BaseModelGenerator {

	protected String classDefineTemplate =
			"/**%n" +
			" * Generated by JFinal, do not modify this file.%n" +
			" */%n" +
			"@SuppressWarnings(\"serial\")%n" +
			"public abstract class %s<M extends %s<M>> extends _BaseModel<M> implements IBean {%n%n";
	
	public ResetBaseModelGenerator(String baseModelPackageName,String baseModelOutputDir) {
		super(baseModelPackageName, baseModelOutputDir);
	}
 
	protected void genClassDefine(TableMeta tableMeta, StringBuilder ret) {
		ret.append(String.format(classDefineTemplate, tableMeta.baseModelName, tableMeta.baseModelName));
	}
}
